apiVersion: management.loft.sh/v1
kind: VirtualClusterInstance
metadata:
  name: cloud-burst
  namespace: p-default
  labels:
    vcluster.com/import-fluxcd: 'true'
    flux-app/podinfo-tailscale: 'true'
    flux-app/tailscale-operator: 'true'
spec:
  displayName: Cloud Burst vCluster
  owner:
    team: loft-admins
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.28.0
      values: |
        controlPlane:
          backingStore:
            etcd:
              embedded:
                enabled: true
          distro:
            k8s:
              image:
                tag: v1.33.4
        privateNodes:
          enabled: true
          vpn:
            enabled: true
            nodeToNode:
              enabled: true
          autoNodes:
            dynamic:
              - name: gcp-beta-node-pool
                provider: gcp-compute-beta-node-provider
                limits:
                  cpu: '30'
                requirements:
                  - property: spot
                    operator: In
                    values:
                      - 'true'
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  clusterRef:
    cluster: loft-cluster
  networkPeer: true
