apiVersion: management.loft.sh/v1
kind: VirtualClusterTemplate
metadata:
  name: private-node-demo-template
spec:
  displayName: Private Nodes Demo Template
  description: This virtual cluster template deploys a virtual cluster with private nodes, configured node pool and has a param to control whether to use spot instances or not.
  template:
    metadata: {}
    instanceTemplate:
      metadata: {}
    pro:
      enabled: true
    helmRelease:
      chart:
        version: 0.29.0
      values: |-
        controlPlane:
          backingStore:
            etcd:
              embedded:
                enabled: true
          distro:
            k8s:
              image:
                tag: v1.34.1
        privateNodes:
          enabled: true
          vpn:
            enabled: true
            nodeToNode:
              enabled: true
          autoNodes:
            dynamic:
              - name: gcp-beta-node-pool
                provider: gcp-compute-beta-node-provider
                limits:
                  cpu: '30'
                requirements:
                  - property: region
                    operator: In
                    values:
                      - {{ .Values.region | quote }}
                  {{if .Values.disableSpot}}
                  - property: spot
                    operator: NotIn
                    values:
                      - 'true'
                  {{end}}
    accessPoint:
      ingress: {}
    spaceTemplate:
      metadata: {}
  parameters:
    - variable: region
      label: GCP Region
      description: "Region for GCP node pool. **IMPORTANT** Updating this parameter for an existing Virtual Cluster Instance created from this template will have no effect."
      type: string
      options:
        - us-east4
        - us-central1
        - us-west2
        - europe-west2
      defaultValue: us-central1
      section: Auto Node Config
    - variable: disableSpot
      label: Disable Spot Instances
      description: >-
        By default, this template is configured to use GCP compute spot instances for private nodes when available. Set this to true to disable the use of spot instances for private nodes.
      type: boolean
      defaultValue: 'false'
      section: Auto Node Config
