apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-labels-exporter-app
  namespace: argocd
  labels:
    feature.demos.vcluster.com: private-nodes
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    # server is the url of the cluster as selected by the spec above
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: .
    repoURL: oci://ghcr.io/sergelogvinov/charts/node-labels-exporter
    targetRevision: 0.1.8
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 20s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m