apiVersion: v1
kind: Secret
metadata:
  name: one-password-sa-token
  namespace: eso
  labels:
    loft.sh/project-secret-name: one-password-sa-token
type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vcp-demo-store
spec:
  provider:
    onepasswordSDK:
      vault: "Solution Architects"
      auth:
        serviceAccountSecretRef:
          name: one-password-sa-token
          namespace: eso
          key: token
      integrationInfo: # this is optional and defaulted
        name: vcp-demo-secrets
        version: v1
    
